FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cluster_store /app/cluster_store

CMD ["python", "cluster_store/cluster_store_server.py"]